name = "IRE Mod"
prefix = "ire_mod"
author = "tsar_bimbo"

files = [
  "docs/",
  "README.md",
  "mod.cpp",
  "meta.cpp"
]

key_name = "{{author}}"

releasebuild = [
  "@zip ire_mod_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]
